// @generated by protoc-gen-es v2.10.1
// @generated from file github/v1/exchange.proto (package github.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file github/v1/exchange.proto.
 */
export declare const file_github_v1_exchange: GenFile;

/**
 * @generated from message github.v1.Token
 */
export declare type Token = Message<"github.v1.Token"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;

  /**
   * @generated from field: google.protobuf.Duration expires_in = 2;
   */
  expiresIn?: Duration;
};

/**
 * Describes the message github.v1.Token.
 * Use `create(TokenSchema)` to create a new message.
 */
export declare const TokenSchema: GenMessage<Token>;

/**
 * @generated from message github.v1.Account
 */
export declare type Account = Message<"github.v1.Account"> & {
  /**
   * @generated from field: string login = 1;
   */
  login: string;

  /**
   * @generated from field: uint32 id = 2;
   */
  id: number;

  /**
   * @generated from field: string node_id = 3;
   */
  nodeId: string;

  /**
   * @generated from field: string gravatar_id = 4;
   */
  gravatarId: string;

  /**
   * @generated from field: github.v1.Account.URLs urls = 5;
   */
  urls?: Account_URLs;

  /**
   * @generated from field: string type = 6;
   */
  type: string;

  /**
   * @generated from field: string user_view_type = 7;
   */
  userViewType: string;

  /**
   * @generated from field: bool site_admin = 8;
   */
  siteAdmin: boolean;

  /**
   * @generated from field: string name = 9;
   */
  name: string;

  /**
   * company
   *
   * @generated from field: string blog = 11;
   */
  blog: string;

  /**
   * location
   *
   * @generated from field: string email = 13;
   */
  email: string;

  /**
   * hireable
   * bio
   * twitter_username
   *
   * @generated from field: string notification_email = 17;
   */
  notificationEmail: string;

  /**
   * @generated from field: uint32 public_repos = 18;
   */
  publicRepos: number;

  /**
   * @generated from field: uint32 public_gists = 19;
   */
  publicGists: number;

  /**
   * @generated from field: uint32 followers = 20;
   */
  followers: number;

  /**
   * @generated from field: uint32 following = 21;
   */
  following: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 22;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 23;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message github.v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export declare const AccountSchema: GenMessage<Account>;

/**
 * @generated from message github.v1.Account.URLs
 */
export declare type Account_URLs = Message<"github.v1.Account.URLs"> & {
  /**
   * @generated from field: string avatar = 1;
   */
  avatar: string;

  /**
   * @generated from field: string api = 2;
   */
  api: string;

  /**
   * @generated from field: string html = 3;
   */
  html: string;

  /**
   * @generated from field: string followers = 4;
   */
  followers: string;

  /**
   * @generated from field: string following = 5;
   */
  following: string;

  /**
   * @generated from field: string gists = 6;
   */
  gists: string;

  /**
   * @generated from field: string starred = 7;
   */
  starred: string;

  /**
   * @generated from field: string subscriptions = 8;
   */
  subscriptions: string;

  /**
   * @generated from field: string organizations = 9;
   */
  organizations: string;

  /**
   * @generated from field: string repos = 10;
   */
  repos: string;

  /**
   * @generated from field: string events = 11;
   */
  events: string;

  /**
   * @generated from field: string received_events = 12;
   */
  receivedEvents: string;
};

/**
 * Describes the message github.v1.Account.URLs.
 * Use `create(Account_URLsSchema)` to create a new message.
 */
export declare const Account_URLsSchema: GenMessage<Account_URLs>;

/**
 * @generated from message github.v1.ExchangeRequest
 */
export declare type ExchangeRequest = Message<"github.v1.ExchangeRequest"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * If set, resulting access token will also be resolved to an `Account`.
   *
   * @generated from field: bool resolve = 3;
   */
  resolve: boolean;
};

/**
 * Describes the message github.v1.ExchangeRequest.
 * Use `create(ExchangeRequestSchema)` to create a new message.
 */
export declare const ExchangeRequestSchema: GenMessage<ExchangeRequest>;

/**
 * @generated from message github.v1.ExchangeResponse
 */
export declare type ExchangeResponse = Message<"github.v1.ExchangeResponse"> & {
  /**
   * @generated from field: github.v1.Token access_token = 1;
   */
  accessToken?: Token;

  /**
   * @generated from field: github.v1.Token refresh_token = 2;
   */
  refreshToken?: Token;

  /**
   * @generated from field: string token_type = 3;
   */
  tokenType: string;

  /**
   * @generated from field: string scope = 4;
   */
  scope: string;

  /**
   * Only set if `ExchangeRequest.resolve` is true.
   *
   * @generated from field: github.v1.Account account = 5;
   */
  account?: Account;
};

/**
 * Describes the message github.v1.ExchangeResponse.
 * Use `create(ExchangeResponseSchema)` to create a new message.
 */
export declare const ExchangeResponseSchema: GenMessage<ExchangeResponse>;

/**
 * @generated from message github.v1.RefreshRequest
 */
export declare type RefreshRequest = Message<"github.v1.RefreshRequest"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * If set, resulting access token will also be resolved to an `Account`.
   *
   * @generated from field: bool resolve = 3;
   */
  resolve: boolean;
};

/**
 * Describes the message github.v1.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export declare const RefreshRequestSchema: GenMessage<RefreshRequest>;

/**
 * @generated from message github.v1.RefreshResponse
 */
export declare type RefreshResponse = Message<"github.v1.RefreshResponse"> & {
  /**
   * @generated from field: github.v1.Token access_token = 1;
   */
  accessToken?: Token;

  /**
   * @generated from field: github.v1.Token refresh_token = 4;
   */
  refreshToken?: Token;

  /**
   * @generated from field: string token_type = 2;
   */
  tokenType: string;

  /**
   * @generated from field: string scope = 3;
   */
  scope: string;

  /**
   * Only set if `RefreshRequest.resolve` is true.
   *
   * @generated from field: github.v1.Account account = 5;
   */
  account?: Account;
};

/**
 * Describes the message github.v1.RefreshResponse.
 * Use `create(RefreshResponseSchema)` to create a new message.
 */
export declare const RefreshResponseSchema: GenMessage<RefreshResponse>;

/**
 * @generated from message github.v1.ResolveRequest
 */
export declare type ResolveRequest = Message<"github.v1.ResolveRequest"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

/**
 * Describes the message github.v1.ResolveRequest.
 * Use `create(ResolveRequestSchema)` to create a new message.
 */
export declare const ResolveRequestSchema: GenMessage<ResolveRequest>;

/**
 * @generated from message github.v1.ResolveResponse
 */
export declare type ResolveResponse = Message<"github.v1.ResolveResponse"> & {
  /**
   * @generated from field: github.v1.Account account = 2;
   */
  account?: Account;
};

/**
 * Describes the message github.v1.ResolveResponse.
 * Use `create(ResolveResponseSchema)` to create a new message.
 */
export declare const ResolveResponseSchema: GenMessage<ResolveResponse>;

/**
 * @generated from service github.v1.ExchangeService
 */
export declare const ExchangeService: GenService<{
  /**
   * @generated from rpc github.v1.ExchangeService.Exchange
   */
  exchange: {
    methodKind: "unary";
    input: typeof ExchangeRequestSchema;
    output: typeof ExchangeResponseSchema;
  },
  /**
   * @generated from rpc github.v1.ExchangeService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshRequestSchema;
    output: typeof RefreshResponseSchema;
  },
  /**
   * @generated from rpc github.v1.ExchangeService.Resolve
   */
  resolve: {
    methodKind: "unary";
    input: typeof ResolveRequestSchema;
    output: typeof ResolveResponseSchema;
  },
}>;

