// @generated by protoc-gen-es v2.10.1
// @generated from file models/v1/models.proto (package models.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file models/v1/models.proto.
 */
export const file_models_v1_models = /*@__PURE__*/
  fileDesc("ChZtb2RlbHMvdjEvbW9kZWxzLnByb3RvEgltb2RlbHMudjEi2QMKBUhhYml0EgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSCwoDc2hhGAMgASgJEg0KBWNvbG9yGAQgASgJEgwKBGljb24YBSABKAkSFAoMZGFpbHlfdGFyZ2V0GAYgASgNEhEKCXRhZ19uYW1lcxgJIAMoCRI2Cgtjb21wbGV0aW9ucxgHIAMoCzIhLm1vZGVscy52MS5IYWJpdC5Db21wbGV0aW9uc0VudHJ5EjQKB2J1dHRvbnMYCCADKAsyIy5tb2RlbHMudjEuQ29tcGxldGlvbi5CdXR0b25PcHRpb25zGqABCg5EaXNwbGF5T3B0aW9ucxIXCgpoaWRlX2NoYXJ0GAEgASgISACIAQESHQoQaGlkZV9wcm9ncmVzc2JhchgCIAEoCEgBiAEBEh0KEGhpZGVfZGVzY3JpcHRpb24YAyABKAhIAogBAUINCgtfaGlkZV9jaGFydEITChFfaGlkZV9wcm9ncmVzc2JhckITChFfaGlkZV9kZXNjcmlwdGlvbhpJChBDb21wbGV0aW9uc0VudHJ5EgsKA2tleRgBIAEoCRIkCgV2YWx1ZRgCIAEoCzIVLm1vZGVscy52MS5Db21wbGV0aW9uOgI4ASKOAQoKQ29tcGxldGlvbhINCgVjb3VudBgBIAEoDRIOCgZ0YXJnZXQYAiABKA0aYQoNQnV0dG9uT3B0aW9ucxIPCgVkZWx0YRgBIAEoDUgAEhQKCnBlcmNlbnRhZ2UYAiABKA1IABISCghjb21wbGV0ZRgDIAEoCEgAEg0KA3NldBgEIAEoDUgAQgYKBGtpbmQiMAoDVGFnEgwKBG5hbWUYASABKAkSDQoFY29sb3IYAiABKAkSDAoEaWNvbhgDIAEoCSKUAQoKQ29sbGVjdGlvbhILCgNzaGEYASABKAkSLQoEdGFncxgCIAMoCzIfLm1vZGVscy52MS5Db2xsZWN0aW9uLlRhZ3NFbnRyeRINCgVvcmRlchgDIAMoCRo7CglUYWdzRW50cnkSCwoDa2V5GAEgASgJEh0KBXZhbHVlGAIgASgLMg4ubW9kZWxzLnYxLlRhZzoCOAFCYQoNY29tLm1vZGVscy52MUILTW9kZWxzUHJvdG9QAaICA01YWKoCCU1vZGVscy5WMcoCCU1vZGVsc1xWMeICFU1vZGVsc1xWMVxHUEJNZXRhZGF0YeoCCk1vZGVsczo6VjFiBnByb3RvMw");

/**
 * Describes the message models.v1.Habit.
 * Use `create(HabitSchema)` to create a new message.
 */
export const HabitSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 0);

/**
 * Describes the message models.v1.Habit.DisplayOptions.
 * Use `create(Habit_DisplayOptionsSchema)` to create a new message.
 */
export const Habit_DisplayOptionsSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 0, 0);

/**
 * Describes the message models.v1.Completion.
 * Use `create(CompletionSchema)` to create a new message.
 */
export const CompletionSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 1);

/**
 * Describes the message models.v1.Completion.ButtonOptions.
 * Use `create(Completion_ButtonOptionsSchema)` to create a new message.
 */
export const Completion_ButtonOptionsSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 1, 0);

/**
 * Describes the message models.v1.Tag.
 * Use `create(TagSchema)` to create a new message.
 */
export const TagSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 2);

/**
 * Describes the message models.v1.Collection.
 * Use `create(CollectionSchema)` to create a new message.
 */
export const CollectionSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 3);

