// @generated by protoc-gen-es v2.10.1
// @generated from file models/v1/models.proto (package models.v1, syntax proto3)
/* eslint-disable */
import type { Message } from "@bufbuild/protobuf"
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2"

/**
 * Describes the file models/v1/models.proto.
 */
export declare const file_models_v1_models: GenFile

/**
 * @generated from message models.v1.Habit
 */
export declare type Habit = Message<"models.v1.Habit"> & {
    /**
     * @generated from field: string name = 1;
     */
    name: string

    /**
     * @generated from field: string description = 2;
     */
    description: string

    /**
     * @generated from field: string sha = 3;
     */
    sha: string

    /**
     * @generated from field: string color = 4;
     */
    color: string

    /**
     * @generated from field: string icon = 5;
     */
    icon: string

    /**
     * @generated from field: uint32 daily_target = 6;
     */
    dailyTarget: number

    /**
     * key is date as `YYYY-MM-DD`
     *
     * @generated from field: map<string, models.v1.Completion> completions = 7;
     */
    completions: { [key: string]: Completion }

    /**
     * defaults to `[{complete: true}]`
     * first button in list is displayed on home page,
     * other buttons are displayed on habit page
     *
     * @generated from field: repeated models.v1.Completion.ButtonOptions buttons = 8;
     */
    buttons: Completion_ButtonOptions[]

    /**
     * @generated from field: models.v1.Habit.DisplayOptions display_options = 9;
     */
    displayOptions?: Habit_DisplayOptions
}

/**
 * Describes the message models.v1.Habit.
 * Use `create(HabitSchema)` to create a new message.
 */
export declare const HabitSchema: GenMessage<Habit>

/**
 * @generated from message models.v1.Habit.DisplayOptions
 */
export declare type Habit_DisplayOptions = Message<"models.v1.Habit.DisplayOptions"> & {
    /**
     * @generated from field: optional bool show_chart = 1;
     */
    showChart?: boolean

    /**
     * @generated from field: optional bool show_progressbar = 2;
     */
    showProgressbar?: boolean

    /**
     * @generated from field: optional bool show_description = 3;
     */
    showDescription?: boolean
}

/**
 * Describes the message models.v1.Habit.DisplayOptions.
 * Use `create(Habit_DisplayOptionsSchema)` to create a new message.
 */
export declare const Habit_DisplayOptionsSchema: GenMessage<Habit_DisplayOptions>

/**
 * @generated from message models.v1.Completion
 */
export declare type Completion = Message<"models.v1.Completion"> & {
    /**
     * @generated from field: uint32 count = 1;
     */
    count: number

    /**
     * @generated from field: uint32 target = 2;
     */
    target: number
}

/**
 * Describes the message models.v1.Completion.
 * Use `create(CompletionSchema)` to create a new message.
 */
export declare const CompletionSchema: GenMessage<Completion>

/**
 * @generated from message models.v1.Completion.ButtonOptions
 */
export declare type Completion_ButtonOptions = Message<"models.v1.Completion.ButtonOptions"> & {
    /**
     * @generated from oneof models.v1.Completion.ButtonOptions.kind
     */
    kind:
        | {
              /**
               * increases count by specified amount
               *
               * @generated from field: uint32 delta = 1;
               */
              value: number
              case: "delta"
          }
        | {
              /**
               * (0, 100], increases count by specified percentage of `target`
               * for example, `percentage = 50` will increase `count` by `target * 0.5`
               *
               * @generated from field: uint32 percentage = 2;
               */
              value: number
              case: "percentage"
          }
        | {
              /**
               * sets `count` to `target`
               *
               * @generated from field: bool complete = 3;
               */
              value: boolean
              case: "complete"
          }
        | {
              /**
               * sets `count` to specified value
               *
               * @generated from field: uint32 set = 4;
               */
              value: number
              case: "set"
          }
        | { case: undefined; value?: undefined }
}

/**
 * Describes the message models.v1.Completion.ButtonOptions.
 * Use `create(Completion_ButtonOptionsSchema)` to create a new message.
 */
export declare const Completion_ButtonOptionsSchema: GenMessage<Completion_ButtonOptions>
