// @generated by protoc-gen-es v2.10.1
// @generated from file models/v1/models.proto (package models.v1, syntax proto3)
 

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file models/v1/models.proto.
 */
export declare const file_models_v1_models: GenFile;

/**
 * @generated from message models.v1.Habit
 */
export declare type Habit = Message<"models.v1.Habit"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: models.v1.Habit.DisplayOptions display_options = 3;
   */
  displayOptions?: Habit_DisplayOptions;

  /**
   * @generated from field: uint32 daily_target = 4;
   */
  dailyTarget: number;

  /**
   * @generated from field: repeated models.v1.Completion completions = 5;
   */
  completions: Completion[];
};

/**
 * Describes the message models.v1.Habit.
 * Use `create(HabitSchema)` to create a new message.
 */
export declare const HabitSchema: GenMessage<Habit>;

/**
 * @generated from message models.v1.Habit.DisplayOptions
 */
export declare type Habit_DisplayOptions = Message<"models.v1.Habit.DisplayOptions"> & {
  /**
   * @generated from field: string color = 1;
   */
  color: string;

  /**
   * @generated from field: string icon = 2;
   */
  icon: string;
};

/**
 * Describes the message models.v1.Habit.DisplayOptions.
 * Use `create(Habit_DisplayOptionsSchema)` to create a new message.
 */
export declare const Habit_DisplayOptionsSchema: GenMessage<Habit_DisplayOptions>;

/**
 * @generated from message models.v1.Completion
 */
export declare type Completion = Message<"models.v1.Completion"> & {
  /**
   * @generated from field: google.protobuf.Timestamp date = 1;
   */
  date?: Timestamp;

  /**
   * @generated from field: uint32 count = 2;
   */
  count: number;
};

/**
 * Describes the message models.v1.Completion.
 * Use `create(CompletionSchema)` to create a new message.
 */
export declare const CompletionSchema: GenMessage<Completion>;

