// @generated by protoc-gen-es v2.10.1
// @generated from file models/v1/models.proto (package models.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file models/v1/models.proto.
 */
export const file_models_v1_models = /*@__PURE__*/
  fileDesc("ChZtb2RlbHMvdjEvbW9kZWxzLnByb3RvEgltb2RlbHMudjEixgMKBUhhYml0EgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSCwoDc2hhGAMgASgJEg0KBWNvbG9yGAQgASgJEgwKBGljb24YBSABKAkSFAoMZGFpbHlfdGFyZ2V0GAYgASgNEjYKC2NvbXBsZXRpb25zGAcgAygLMiEubW9kZWxzLnYxLkhhYml0LkNvbXBsZXRpb25zRW50cnkSNAoHYnV0dG9ucxgIIAMoCzIjLm1vZGVscy52MS5Db21wbGV0aW9uLkJ1dHRvbk9wdGlvbnMaoAEKDkRpc3BsYXlPcHRpb25zEhcKCmhpZGVfY2hhcnQYASABKAhIAIgBARIdChBoaWRlX3Byb2dyZXNzYmFyGAIgASgISAGIAQESHQoQaGlkZV9kZXNjcmlwdGlvbhgDIAEoCEgCiAEBQg0KC19oaWRlX2NoYXJ0QhMKEV9oaWRlX3Byb2dyZXNzYmFyQhMKEV9oaWRlX2Rlc2NyaXB0aW9uGkkKEENvbXBsZXRpb25zRW50cnkSCwoDa2V5GAEgASgJEiQKBXZhbHVlGAIgASgLMhUubW9kZWxzLnYxLkNvbXBsZXRpb246AjgBIo4BCgpDb21wbGV0aW9uEg0KBWNvdW50GAEgASgNEg4KBnRhcmdldBgCIAEoDRphCg1CdXR0b25PcHRpb25zEg8KBWRlbHRhGAEgASgNSAASFAoKcGVyY2VudGFnZRgCIAEoDUgAEhIKCGNvbXBsZXRlGAMgASgISAASDQoDc2V0GAQgASgNSABCBgoEa2luZEJhCg1jb20ubW9kZWxzLnYxQgtNb2RlbHNQcm90b1ABogIDTVhYqgIJTW9kZWxzLlYxygIJTW9kZWxzXFYx4gIVTW9kZWxzXFYxXEdQQk1ldGFkYXRh6gIKTW9kZWxzOjpWMWIGcHJvdG8z");

/**
 * Describes the message models.v1.Habit.
 * Use `create(HabitSchema)` to create a new message.
 */
export const HabitSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 0);

/**
 * Describes the message models.v1.Habit.DisplayOptions.
 * Use `create(Habit_DisplayOptionsSchema)` to create a new message.
 */
export const Habit_DisplayOptionsSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 0, 0);

/**
 * Describes the message models.v1.Completion.
 * Use `create(CompletionSchema)` to create a new message.
 */
export const CompletionSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 1);

/**
 * Describes the message models.v1.Completion.ButtonOptions.
 * Use `create(Completion_ButtonOptionsSchema)` to create a new message.
 */
export const Completion_ButtonOptionsSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 1, 0);

