// @generated by protoc-gen-es v2.10.1
// @generated from file models/v1/models.proto (package models.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file models/v1/models.proto.
 */
export const file_models_v1_models = /*@__PURE__*/
  fileDesc("ChZtb2RlbHMvdjEvbW9kZWxzLnByb3RvEgltb2RlbHMudjEilgEKBUhhYml0EgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSCwoDc2hhGAMgASgJEg0KBWNvbG9yGAQgASgJEgwKBGljb24YBSABKAkSFAoMZGFpbHlfdGFyZ2V0GAYgASgNEioKC2NvbXBsZXRpb25zGAcgAygLMhUubW9kZWxzLnYxLkNvbXBsZXRpb24iRQoKQ29tcGxldGlvbhIoCgRkYXRlGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBINCgVjb3VudBgCIAEoDUJhCg1jb20ubW9kZWxzLnYxQgtNb2RlbHNQcm90b1ABogIDTVhYqgIJTW9kZWxzLlYxygIJTW9kZWxzXFYx4gIVTW9kZWxzXFYxXEdQQk1ldGFkYXRh6gIKTW9kZWxzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message models.v1.Habit.
 * Use `create(HabitSchema)` to create a new message.
 */
export const HabitSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 0);

/**
 * Describes the message models.v1.Completion.
 * Use `create(CompletionSchema)` to create a new message.
 */
export const CompletionSchema = /*@__PURE__*/
  messageDesc(file_models_v1_models, 1);

